services:
  node:
    image: node:25.2.1-alpine3.22
    user: node
    working_dir: /home/node
    tty: true
    stdin_open: true
    volumes:
      - .:/home/node
    ports:
      - 8000:8000
      - 8001:8001
