name: Continous Integration
on:
  push:
    branches:
      - development
jobs:
  continuous-integration:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the project
        uses: actions/checkout@v5
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 25.2.1
          cache: npm
      - name: Install dependencies
        run: npm ci
      - name: Audit the dependencies
        run: npm audit
      - name: Build the server
        run: npm -w applications/server run build
      - name: Build the Web client
        run: npm -w applications/web run build
