name: Continous Integration
on:
  push:
    branches:
      - development
jobs:
  continuous-integration:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the project
        uses: actions/checkout@v5
      - name: Start the Docker Compose services
        run: docker compose up -d
      - name: Install the dependencies
        run: docker compose exec hello-server npm i
      - name: Audit Node.js packages
        run: docker compose exec hello-server npm audit
      - name: Build the server application
        run: docker compose exec hello-server npm -w applications/server run build
      - name: Build the Web application
        run: docker compose exec hello-web npm -w applications/web run build
      - name: Stop the Docker Compose services
        run: docker compose down --remove-orphans --volumes --timeout 0
